name: Tests
on: [pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        working-directory: packages/plugin
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Run tests
        working-directory: packages/plugin
        run: npm run coverage

      - name: Coveralls
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
          directory: packages/plugin/coverage
